//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD5SumTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class test_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal test_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD5SumTest.test_resources", typeof(test_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ackermann_msgs/AckermannDrive 3512e91b48d69674a0e86fadf1ea8231
        ///ackermann_msgs/AckermannDriveStamped 1fd5d7f58889cefd44d29f6653240d0c
        ///actionlib_msgs/GoalID 302881f31927c1df708a2dbab0e80ee8
        ///actionlib_msgs/GoalStatusArray 8b2b82f13216d0a8ea88bd3af735e619
        ///actionlib_msgs/GoalStatus d388f9b87b3c471f784434d671988d4a
        ///actionlib/TestAction 991e87a72802262dfbe5d1b3cf6efc9a
        ///actionlib/TestActionFeedback 6d3d0bf7fb3dda24779c010a9f3eb7cb
        ///actionlib/TestActionGoal 348369c5b403676156094e8c159720bf
        ///actionlib/TestActio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msg_sums {
            get {
                return ResourceManager.GetString("msg_sums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ackermann_msgs/AckermannDrive 3512e91b48d69674a0e86fadf1ea8231
        ///ackermann_msgs/AckermannDriveStamped 1fd5d7f58889cefd44d29f6653240d0c
        ///actionlib_msgs/GoalID 302881f31927c1df708a2dbab0e80ee8
        ///actionlib_msgs/GoalStatusArray 8b2b82f13216d0a8ea88bd3af735e619
        ///actionlib_msgs/GoalStatus d388f9b87b3c471f784434d671988d4a
        ///actionlib/TestAction 991e87a72802262dfbe5d1b3cf6efc9a
        ///actionlib/TestActionFeedback 6d3d0bf7fb3dda24779c010a9f3eb7cb
        ///actionlib/TestActionGoal 348369c5b403676156094e8c159720bf
        ///actionlib/TestActio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string srv_sums {
            get {
                return ResourceManager.GetString("srv_sums", resourceCulture);
            }
        }
    }
}
